name: Build and Push Docker Image

on:
  push:
    branches:
      - main  
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag for the Docker image'
        required: true
        default: 'latest'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: "mahmoudazaid"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v4
      with:
        path: ~/.cache/docker
        key: ${{ runner.os }}-docker-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract version from Dockerfile
      id: extract_version
      run: |
        VERSION=$(grep -m 1 'LABEL BUILD_TOOLS' Dockerfile | cut -d '=' -f2 | tr -d '"')
        if [ -z "$VERSION" ]; then
          VERSION=$(grep -m 1 'ENV BUILD_TOOLS' Dockerfile | cut -d '=' -f2 | tr -d '"')
        fi
        echo "VERSION=$VERSION"
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Extract build tools version
      id: extract_build_tools
      run: |
        BUILD_TOOLS_VERSION=$(grep -m 1 'ENV BUILD_TOOLS' Dockerfile | cut -d '=' -f2 | tr -d '"')
        echo "BUILD_TOOLS_VERSION=$BUILD_TOOLS_VERSION"
        echo "BUILD_TOOLS_VERSION=$BUILD_TOOLS_VERSION" >> $GITHUB_ENV

    - name: Build Docker image
      run: |
        docker build -t ${{ env.DOCKER_USERNAME }}/android-build-tools:${{ env.VERSION }} .
        docker build -t ${{ env.DOCKER_USERNAME }}/android-build-tools:latest .

    - name: Push Docker image
      run: |
        docker push ${{ env.DOCKER_USERNAME }}/android-build-tools:${{ env.VERSION }}
        docker push ${{ env.DOCKER_USERNAME }}/android-build-tools:latest

    - name: Clean up Docker images
      run: |
        docker image prune -af

    - name: Trigger android-images Repository Workflow
      if: success()
      run: |
        curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.TRIGGER_REPO_TOKEN }}" \
          $TARGET_REPO \
          -d '{"event_type": "docker-image-updated", "client_payload": {"version": "${{ env.VERSION }}", "build_tools_version": "${{ env.BUILD_TOOLS_VERSION }}"}}'
      env:
        TARGET_REPO: "https://api.github.com/repos/mahmoudazaid/android-images/dispatches"