name: Docker Image Health Check

on:
  pull_request:
    branches:
      - master 

jobs:
  docker-build-run:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: "mahmoudazaid"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        install: true

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image for linux/amd64
      run: |
        docker buildx build \
          --platform linux/amd64 \
          -t ${{ env.DOCKER_USERNAME }}/android-build-tools:${{ github.sha }} \
          -t ${{ env.DOCKER_USERNAME }}/android-build-tools:latest \
          --load .

    - name: Test Docker Image on linux/amd64
      run: |
        echo "Testing Docker image on linux/amd64"
        docker run --platform linux/amd64 -d --name test-android-build-tools-amd64 ${{ env.DOCKER_USERNAME }}/android-build-tools:${{ github.sha }}
        sleep 10
        docker ps -a
        docker logs test-android-build-tools-amd64
      env:
        PLATFORM: linux/amd64

    - name: Clean up
      run: |
        docker stop test-android-build-tools-amd64 || true
        docker rm test-android-build-tools-amd64 || true