name: Docker Image Health Check

on:
  pull_request:
    branches:
      - master 

jobs:
  docker-build-run:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: "mahmoudazaid"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        install: true

    - name: Install QEMU for Multi-Architecture Support
      uses: docker/setup-qemu-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Multi-Architecture Docker Image and Export as OCI Tar
      run: |
        docker buildx build \
          --platform linux/amd64,linux/arm64/v8 \
          -t ${{ env.DOCKER_USERNAME }}/android-build-tools:${{ github.sha }} \
          -t ${{ env.DOCKER_USERNAME }}/android-build-tools:latest \
          --output type=oci,dest=/tmp/android-build-tools.tar .

    - name: Load Docker Image from OCI Tar
      run: |
        cat /tmp/android-build-tools.tar | docker import - mahmoudazaid/android-build-tools:${{ github.sha }}

    - name: Test Docker Image on linux/amd64
      run: |
        echo "Testing Docker image on linux/amd64"
        docker run --platform linux/amd64 -d --name test-android-build-tools-amd64 mahmoudazaid/android-build-tools:${{ github.sha }}
        sleep 10
        docker ps -a
        docker logs test-android-build-tools-amd64
      env:
        PLATFORM: linux/amd64

    - name: Test Docker Image on linux/arm64/v8
      run: |
        echo "Testing Docker image on linux/arm64/v8"
        docker run --platform linux/arm64/v8 -d --name test-android-build-tools-arm64 mahmoudazaid/android-build-tools:${{ github.sha }}
        sleep 10
        docker ps -a
        docker logs test-android-build-tools-arm64
      env:
        PLATFORM: linux/arm64/v8

    - name: Clean up
      run: |
        docker stop test-android-build-tools-amd64 || true
        docker stop test-android-build-tools-arm64 || true
        docker rm test-android-build-tools-amd64 || true
        docker rm test-android-build-tools-arm64 || true