name: Build and Push Docker Image

on:
  push:
    branches:
      - main  
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag for the Docker image'
        required: true
        default: 'latest'
  repository_dispatch:
    types: [docker-image-updated]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: "mahmoudazaid"
      DOCKER_SCOUT_VERSION: "1.15.0" # Docker Scout version
      ANDROID_BUILD_TOOLS_VERSION: "${{ env.VERSION }}" # Set Android Build Tools version to match Dockerfile version
      IMAGE_TAG: "${{ github.event.inputs.version }}" # Default to latest from the workflow dispatch
      VERSION: "${{ env.IMAGE_TAG }}" # Version from dispatch or input
      BUILD_TOOLS_VERSION: "${{ github.event.client_payload.build_tools_version }}" # Extracted build-tools version from the payload
      CHECKOUT_ACTION_VERSION: "v4" # actions/checkout version
      BUILDX_ACTION_VERSION: "v3" # docker/setup-buildx-action version
      LOGIN_ACTION_VERSION: "v3" # docker/login-action version

    steps:
    - name: Checkout repository
      uses: actions/checkout@${{ env.CHECKOUT_ACTION_VERSION }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@${{ env.BUILDX_ACTION_VERSION }}

    - name: Cache Docker layers
      uses: actions/cache@v4
      with:
        path: ~/.cache/docker
        key: ${{ runner.os }}-docker-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Log in to Docker Hub
      uses: docker/login-action@${{ env.LOGIN_ACTION_VERSION }}
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract version from Dockerfile
      id: extract_version
      run: |
        VERSION=$(grep -m 1 'LABEL BUILD_TOOLS' Dockerfile | cut -d '=' -f2 | tr -d '"')
        if [ -z "$VERSION" ]; then
          VERSION=$(grep -m 1 'ENV BUILD_TOOLS' Dockerfile | cut -d '=' -f2 | tr -d '"')
        fi
        echo "VERSION=$VERSION"
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Extract build tools version
      id: extract_build_tools
      run: |
        BUILD_TOOLS_VERSION=$(grep -m 1 'ENV BUILD_TOOLS' Dockerfile | cut -d '=' -f2 | tr -d '"')
        echo "BUILD_TOOLS_VERSION=$BUILD_TOOLS_VERSION"
        echo "BUILD_TOOLS_VERSION=$BUILD_TOOLS_VERSION" >> $GITHUB_ENV

    - name: Build Docker image
      run: |
        docker build -t ${{ env.DOCKER_USERNAME }}/android-build-tools:${{ env.VERSION }} .
        docker build -t ${{ env.DOCKER_USERNAME }}/android-build-tools:latest .

    - name: Install Docker Scout v${{ env.DOCKER_SCOUT_VERSION }}
      run: |
        curl -fsSL https://github.com/docker/scout-cli/releases/download/v${{ env.DOCKER_SCOUT_VERSION }}/docker-scout_${{ env.DOCKER_SCOUT_VERSION }}_linux_amd64.tar.gz | tar xz -C /usr/local/bin
        scout --version  # Confirm installation

    - name: Run Docker Scout to scan the image for vulnerabilities
      run: |
        docker scout start ${{ env.DOCKER_USERNAME }}/android-build-tools:${{ env.VERSION }}
        docker scout start ${{ env.DOCKER_USERNAME }}/android-build-tools:latest

    - name: Push Docker image
      run: |
        docker push ${{ env.DOCKER_USERNAME }}/android-build-tools:${{ env.VERSION }}
        docker push ${{ env.DOCKER_USERNAME }}/android-build-tools:latest

    - name: Clean up Docker images
      run: |
        docker image prune -af

    - name: Trigger android-images Repository Workflow
      if: success()
      run: |
        curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.TRIGGER_REPO_TOKEN }}" \
          $TARGET_REPO \
          -d '{"event_type": "docker-image-updated", "client_payload": {"version": "${{ env.VERSION }}", "build_tools_version": "${{ env.BUILD_TOOLS_VERSION }}"}}'
      env:
        TARGET_REPO: "https://api.github.com/repos/mahmoudazaid/android-images/dispatches"
