name: Build and Push Docker Image

on:
  push:
    branches:
      - main  
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag for the Docker image'
        required: true
        default: 'latest'
  repository_dispatch:
    types: [docker-image-updated]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: "mahmoudazaid"
      DOCKER_SCOUT: https://github.com/docker/scout-cli/releases/download/v1.15.0/docker-scout_1.15.0_linux_amd64.tar.gz
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set version and build tools version
      id: set_version
      run: |
        # Set VERSION based on input from the dispatch event or workflow dispatch
        if [[ -n "${{ github.event.inputs.version }}" ]]; then
          echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
        elif [[ -n "${{ github.event.client_payload.version }}" ]]; then
          echo "VERSION=${{ github.event.client_payload.version }}" >> $GITHUB_ENV
        else
          VERSION="latest"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
        fi

        # Set BUILD_TOOLS_VERSION from the payload
        echo "BUILD_TOOLS_VERSION=${{ github.event.client_payload.build_tools_version }}" >> $GITHUB_ENV
        echo "ANDROID_BUILD_TOOLS_VERSION=${{ env.VERSION }}" >> $GITHUB_ENV
        echo "IMAGE_TAG=${{ env.VERSION }}" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Cache Docker layers
      uses: actions/cache@v4
      with:
        path: ~/.cache/docker
        key: ${{ runner.os }}-docker-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract version from Dockerfile
      id: extract_version
      run: |
        VERSION=$(grep -m 1 'LABEL BUILD_TOOLS' Dockerfile | cut -d '=' -f2 | tr -d '"')
        if [ -z "$VERSION" ]; then
          VERSION=$(grep -m 1 'ENV BUILD_TOOLS' Dockerfile | cut -d '=' -f2 | tr -d '"')
        fi
        echo "VERSION=$VERSION"
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Build Docker image
      run: |
        docker build -t ${{ env.DOCKER_USERNAME }}/android-build-tools:${{ env.VERSION }} .
        docker build -t ${{ env.DOCKER_USERNAME }}/android-build-tools:latest .

    - name: Install Docker Scout ${{ env.DOCKER_SCOUT }}
      run: |
        curl -fsSL ${{ env.DOCKER_SCOUT }} | tar xz -C /usr/local/bin
        sudo ln -s /usr/local/bin/docker-scout /usr/bin/scout
        docker-scout version

    - name: Run Docker Scout to scan the image for vulnerabilities
      run: |
        docker-scout cves ${{ env.DOCKER_USERNAME }}/android-build-tools:${{ env.VERSION }}
        docker-scout cves ${{ env.DOCKER_USERNAME }}/android-build-tools:latest

    - name: Push Docker image
      run: |
        docker push ${{ env.DOCKER_USERNAME }}/android-build-tools:${{ env.VERSION }}
        docker push ${{ env.DOCKER_USERNAME }}/android-build-tools:latest

    - name: Clean up Docker images
      run: |
        docker image prune -af

    - name: Trigger android-images Repository Workflow
      if: success()
      run: |
        curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.TRIGGER_REPO_TOKEN }}" \
          $TARGET_REPO \
          -d '{"event_type": "docker-image-updated", "client_payload": {"version": "${{ env.VERSION }}", "build_tools_version": "${{ env.BUILD_TOOLS_VERSION }}"}}'
      env:
        TARGET_REPO: "https://api.github.com/repos/mahmoudazaid/android-images/dispatches"